stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:latest
  services:
  - docker:dind
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - echo "=====Build and Push Docker Image====="
    - cd app
    - docker build . -t fiardika/privy:$CI_COMMIT_SHORT_SHA . 
    - docker push fiardika/privy:$CI_COMMIT_SHORT_SHA
    - echo "=====Build and Push Complete====="

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  before_script:
    - chmod 400 $PEM
  script:
  - ssh -o StrictHostKeyChecking=no -i $PEM ubuntu@$EC2_IP"
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD &&
    docker ps -aq | xargs docker stop | xargs docker rm &&
    docker run -d -p 3000:3000 fiardika/privy:$CI_COMMIT_SHORT_SHA"