stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  image: docker:latest
  services:
  - docker:dind
  stage: build
  before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - echo "=====Build and Push Docker Image====="
    - cd app
    - docker build . -t fiardika/privy:latest
    - docker push fiardika/privy:latest
    - echo "=====Build and Push Complete====="

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  before_script:
    - apt-get install openssh-server
    - echo "$PEM" > dell.pem
  script:
  - ssh -i dell.pem ubuntu@"EC2_IP"
  - docker run -it 3000:3000 fiardika/privy:latest